# -> War im Unterricht
- -> Ken ich auch so

Komponenten:
#Transform
#Riggidbody(2D)
#Collider...(2D)
#animator
-CharacterControler
-MeshRenderer
#SpriteRenderer
-TilemapRenderer
-Light
-RectTransform
-Grid
-Tilemap

Methoden:
#Update()
#Start()
#Normelize()
#Destroy()
#Instantiate(Gameobject, position, rotation)
#Rotate()
#GetComponent<T>()
-FindComponent<T>()
-Awake()
-FixedUpdate()
#OnColliderEnter/Exit/Stay()
-OnTriggerEnter/Exit/Stay()

Dateitypen:
#.png
#.cs
-.bink
-.fbx
-.obj
-.txt
-.json
-.asset
#.packeg
#.controller
#.anim
#.meta
-.unity
#.prefab
-.mat
-.shader